server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: core-app
          uri: http://localhost:8081
          predicates:
            - Path: /api/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path: /auth/**