server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: core-app
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter


jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwMTIzNDU2Nzg=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8585/eureka